"""
02_validate_PI_sciplex.py
──────────────────────────
Validate atomic PI against the monocle3-based reference PI (SciPlex paper)
across three LOO-filtered gene lists (r≥0.2, r≥0.3, r≥0.4).

PURPOSE
───────
Demonstrates that our simple PI formula reproduces the published monocle3
proliferation_index on the public SciPlex3 dataset, and shows how correlation
changes with LOO-filtering stringency.

PREREQUISITE
────────────
Run 01_gene_LOO_correlation.py first — it generates:
  gene_lists/cc_genes_r02.json
  gene_lists/cc_genes_r03.json
  gene_lists/cc_genes_r04.json

WHAT IS COMPARED
────────────────
For each threshold (r≥0.2, r≥0.3, r≥0.4) and also the full 100-gene pool:
  atomic_PI  = log1p( (Σ_S + Σ_G2M raw counts) / nCount_RNA )
  reference  = monocle3 proliferation_index  (published, in adata.obs)

Spearman r and Pearson r are reported both overall and per cell type.

USAGE
─────
  conda run -n scvi python 02_validate_PI_sciplex.py

  # Custom paths
  conda run -n scvi python 02_validate_PI_sciplex.py \\
      --sciplex /path/to/sciplex3_atomicPI2.symbolVar.h5ad \\
      --gene-list-dir gene_lists/ \\
      --out results/

MEMORY ESTIMATE
───────────────
  581,777 cells × 100 CC genes × 4 B ≈ 233 MB
  (same matrix reused across all threshold comparisons)
  Recommended: ≥ 2 GB RAM
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr, pearsonr

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))
from pi_functions import compute_pi, load_cc_counts, load_gene_dict

# ─── Default paths ────────────────────────────────────────────────────────────
_BASE = Path("/mnt/lab-store/projects/ATOMIC/analysis/dong")
DEFAULT_SCIPLEX      = _BASE / "object/SciPlexGxE/sciplex3_atomicPI2.symbolVar.h5ad"
DEFAULT_GENE_LIST_DIR = ROOT / "gene_lists"
DEFAULT_OUT          = ROOT / "results"
MONOCLE3_PI_KEY      = "proliferation_index"
CELLTYPE_KEY         = "cell_type"


def parse_args():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--sciplex",        default=str(DEFAULT_SCIPLEX),       help="Path to SciPlex3 symbolVar h5ad")
    p.add_argument("--gene-list-dir",  default=str(DEFAULT_GENE_LIST_DIR), help="Directory containing gene list JSONs")
    p.add_argument("--out",            default=str(DEFAULT_OUT),           help="Output directory")
    p.add_argument("--no-plot",        action="store_true",                 help="Skip matplotlib figures")
    return p.parse_args()


# ─── Helpers ──────────────────────────────────────────────────────────────────

def compute_pi_for_genelist(
    counts: np.ndarray,
    libsize: np.ndarray,
    present_genes: list[str],
    gene_dict: dict,
) -> np.ndarray:
    """Compute PI given a counts matrix (pre-loaded for the 100-gene pool)."""
    gene_to_col = {g: i for i, g in enumerate(present_genes)}
    s_idx   = [gene_to_col[g] for g in gene_dict["s.genes"]   if g in gene_to_col]
    g2m_idx = [gene_to_col[g] for g in gene_dict["g2m.genes"] if g in gene_to_col]
    return compute_pi(counts, libsize, s_idx, g2m_idx)


def correlation_stats(a: np.ndarray, b: np.ndarray) -> dict:
    r_sp, p_sp = spearmanr(a, b)
    r_pe, p_pe = pearsonr(a, b)
    return {"spearman_r": r_sp, "spearman_p": p_sp,
            "pearson_r":  r_pe, "pearson_p":  p_pe,
            "n": len(a)}


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    args = parse_args()
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    gene_list_dir = Path(args.gene_list_dir)

    if not Path(args.sciplex).exists():
        print(f"ERROR: SciPlex3 file not found: {args.sciplex}")
        sys.exit(1)

    # ── Discover gene list files ──────────────────────────────────────────────
    # Always include the full 100-gene pool as baseline.
    # The threshold-filtered files are generated by 01_gene_LOO_correlation.py.
    configs = []  # list of (label, json_path)

    pool_json = gene_list_dir / "cc_genes_pool.json"
    if pool_json.exists():
        configs.append(("pool_100", pool_json))

    for thr_tag, label in [("r02", "r≥0.2"), ("r03", "r≥0.3"), ("r04", "r≥0.4")]:
        p = gene_list_dir / f"cc_genes_{thr_tag}.json"
        if p.exists():
            configs.append((label, p))
        else:
            print(f"[WARN] {p.name} not found — run 01_gene_LOO_correlation.py first.")

    if not configs:
        print("No gene list files found. Exiting.")
        sys.exit(1)

    # ── Load the full 100-gene pool counts (shared across all comparisons) ────
    # Load counts for the union of all genes across all gene lists
    all_genes_union: list[str] = []
    seen = set()
    for _, jp in configs:
        gd = load_gene_dict(jp)
        for g in gd["s.genes"] + gd["g2m.genes"]:
            if g not in seen:
                all_genes_union.append(g)
                seen.add(g)

    print(f"Loading SciPlex3 counts for {len(all_genes_union)} unique CC genes...")
    counts, libsize, present_genes, missing = load_cc_counts(args.sciplex, all_genes_union)
    print(f"  Cells: {counts.shape[0]:,}  |  genes found: {len(present_genes)}/{len(all_genes_union)}")
    if missing:
        print(f"  Missing from dataset: {missing}")
    print(f"  Counts matrix: {counts.nbytes / 1e6:.0f} MB")

    # ── Load reference PI + cell type ─────────────────────────────────────────
    import anndata as ad
    adata = ad.read_h5ad(args.sciplex, backed="r")
    ref_pi    = adata.obs[MONOCLE3_PI_KEY].values.astype(float)
    celltypes = adata.obs[CELLTYPE_KEY].values if CELLTYPE_KEY in adata.obs.columns else None
    adata.file.close()

    print(f"  Reference PI (monocle3): min={ref_pi.min():.4f}, "
          f"mean={ref_pi.mean():.4f}, max={ref_pi.max():.4f}")

    # ── Compute PI + correlations for each gene list ──────────────────────────
    print(f"\n{'═'*70}")
    print(f"{'Gene list':<12} {'n_genes':>7} {'n_S':>5} {'n_G2M':>6}  "
          f"{'Spearman r':>10}  {'Pearson r':>9}")
    print("═"*70)

    summary_records = []
    per_cell_scores = {"monocle3_pi": ref_pi}
    if celltypes is not None:
        per_cell_scores["cell_type"] = celltypes

    for label, json_path in configs:
        gd = load_gene_dict(json_path)
        n_s   = len(gd["s.genes"])
        n_g2m = len(gd["g2m.genes"])
        n_tot = n_s + n_g2m

        atomic_pi = compute_pi_for_genelist(counts, libsize, present_genes, gd)
        stats_all = correlation_stats(atomic_pi, ref_pi)

        print(f"  {label:<10} {n_tot:>7}  {n_s:>5}  {n_g2m:>6}  "
              f"{stats_all['spearman_r']:>10.4f}  {stats_all['pearson_r']:>9.4f}")

        per_cell_scores[f"atomic_pi_{label.replace('≥','').replace('.','').replace(' ','')}"] = atomic_pi

        row = {"gene_list": label, "n_total": n_tot, "n_S": n_s, "n_G2M": n_g2m}
        row.update(stats_all)

        # Per cell-type breakdown
        if celltypes is not None:
            for ct in sorted(set(celltypes)):
                mask = celltypes == ct
                if mask.sum() < 50:
                    continue
                ct_stats = correlation_stats(atomic_pi[mask], ref_pi[mask])
                row[f"r_sp_{ct}"] = ct_stats["spearman_r"]
                row[f"r_pe_{ct}"] = ct_stats["pearson_r"]

        summary_records.append(row)

    print("═"*70)

    # ── Per cell-type detail ──────────────────────────────────────────────────
    if celltypes is not None:
        unique_cts = sorted(set(celltypes))
        print(f"\nPer cell-type Spearman r:")
        header = f"  {'Gene list':<12}" + "".join(f"  {ct[:10]:>10}" for ct in unique_cts)
        print(header)
        print("  " + "─" * (len(header) - 2))
        for rec in summary_records:
            row_str = f"  {rec['gene_list']:<12}"
            for ct in unique_cts:
                val = rec.get(f"r_sp_{ct}", float("nan"))
                row_str += f"  {val:>10.4f}"
            print(row_str)

    # ── Save ─────────────────────────────────────────────────────────────────
    df_summary = pd.DataFrame(summary_records)
    out_summary = out_dir / "validation_summary.csv"
    df_summary.to_csv(out_summary, index=False)
    print(f"\nSummary saved → {out_summary}")

    df_scores = pd.DataFrame(per_cell_scores)
    out_scores = out_dir / "validation_scores.csv"
    df_scores.to_csv(out_scores, index=False)
    print(f"Per-cell scores → {out_scores}")

    # ── Scatter plots ─────────────────────────────────────────────────────────
    if not args.no_plot:
        try:
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt

            n_configs = len(configs)
            fig, axes = plt.subplots(1, n_configs, figsize=(4 * n_configs, 4), squeeze=False)

            rng = np.random.default_rng(42)
            n_plot = min(15000, len(ref_pi))
            idx_plot = rng.choice(len(ref_pi), n_plot, replace=False)

            for ax, (label, json_path), rec in zip(axes[0], configs, summary_records):
                col_key = f"atomic_pi_{label.replace('≥','').replace('.','').replace(' ','')}"
                atomic_pi = per_cell_scores[col_key]
                n_s, n_g2m = rec["n_S"], rec["n_G2M"]

                if celltypes is not None:
                    cmap = plt.get_cmap("tab10")
                    cts = sorted(set(celltypes))
                    for i, ct in enumerate(cts):
                        m = celltypes[idx_plot] == ct
                        ax.scatter(ref_pi[idx_plot][m], atomic_pi[idx_plot][m],
                                   s=1, alpha=0.3, color=cmap(i % 10),
                                   label=ct, rasterized=True)
                    if ax is axes[0][0]:
                        ax.legend(markerscale=5, fontsize=6, loc="upper left",
                                  title=CELLTYPE_KEY, title_fontsize=6)
                else:
                    ax.scatter(ref_pi[idx_plot], atomic_pi[idx_plot],
                               s=1, alpha=0.3, color="steelblue", rasterized=True)

                r_sp = rec["spearman_r"]
                r_pe = rec["pearson_r"]
                ax.set_title(f"{label}  (S={n_s}, G2M={n_g2m})\n"
                             f"Spearman r={r_sp:.3f}  Pearson r={r_pe:.3f}", fontsize=9)
                ax.set_xlabel("monocle3 PI (reference)", fontsize=8)
                ax.set_ylabel("atomic PI", fontsize=8)

            fig.suptitle(f"SciPlex3 validation  (n={len(ref_pi):,} cells, plotted: {n_plot:,})",
                         fontsize=10, y=1.02)
            fig.tight_layout()
            out_fig = out_dir / "validation_scatter.png"
            fig.savefig(out_fig, dpi=150, bbox_inches="tight")
            plt.close(fig)
            print(f"Scatter plots → {out_fig}")

        except ImportError:
            print("[WARN] matplotlib not available — skipping plot.")


if __name__ == "__main__":
    main()
